default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: rails_movie_api_development

test:
  <<: *default
  database: rails_movie_api_test

# As with config/credentials.yml, you never want to store sensitive information,
# like your database password, in your source code. If your source code is
# ever seen by anyone, they now have access to your database.
#
# Instead, provide the password or a full connection URL as an environment
# variable when you boot the app. For example:
#
#   DATABASE_URL="postgres://myuser:mypass@localhost/somedatabase"
#
# If the connection URL is provided in the special DATABASE_URL environment
# variable, Rails will automatically merge its configuration values on top of
# the values provided in this file. Alternatively, you can specify a connection
# URL environment variable explicitly:
#
#   production:
#     url: <%= ENV["MY_APP_DATABASE_URL"] %>
#
# Read https://guides.rubyonrails.org/configuring.html#configuring-a-database
# for a full overview on how database connection configuration can be specified.
#

# TODO: Using the same DB for now; split by role later
production:
  primary:
    <<: *default
    url: <%= Rails.application.credentials.database_url %>
  cable:
    <<: *default
    url: <%= Rails.application.credentials.database_url %>
  queue:
    <<: *default
    url: <%= Rails.application.credentials.database_url %>
  cache:
    <<: *default
    url: <%= Rails.application.credentials.database_url %>

# production:
#   primary: &primary_production
#     <<: *default
#     database: rails_movie_api_production
#     username: rails_movie_api
#     password: <%= ENV["RAILS_MOVIE_API_DATABASE_PASSWORD"] %>
#   cache:
#     <<: *primary_production
#     database: rails_movie_api_production_cache
#     migrations_paths: db/cache_migrate
#   queue:
#     <<: *primary_production
#     database: rails_movie_api_production_queue
#     migrations_paths: db/queue_migrate
#   cable:
#     <<: *primary_production
#     database: rails_movie_api_production_cable
#     migrations_paths: db/cable_migrate
